### ISSUE TITLE
Building animation spinner off center

### ISSUE THREAD

**Issue by nalanj** [cschleiden/vscode-github-actions#76]
I don't have time to dig into why, but the building status image is spinning off center:

![Peek 2021-02-18 12-30](https://user-images.githubusercontent.com/5594/108396790-3ffe1e00-71e5-11eb-83d8-71031dacbaea.gif)

**Comment by MicaelJarniac** [comment]
Just noticed this too.
![GIF](https://thumbs.gfycat.com/IncompatibleHonestBeaver-size_restricted.gif)

**Comment by cschleiden** [comment]
That's a bug in VS Code, investigated and filed here: https://github.com/microsoft/vscode/issues/117859

**Comment by cschleiden** [comment]
Should be fixed in the next release!

**Comment by RobertLbebber** [comment]
Still exists in the bottom corner on the status bar for version 1.70.2 (say for deleting a large folder)
